### ISSUE TITLE
Creating project plan

### ISSUE THREAD

**Issue by Merlin1674** [Merlin1674/Capstone-Toxic_Comment_Classification#1]
- [x] Defining the minimum goal.
- [x] Creating List of further goals.
- [ ] First project plan.
